### PR TITLE
Food lists and shopping lists

### PR DESCRIPTION
**Pull request by richie1988**
##Created the foodlist and the recipe
## Food list:

- Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
- Should lead to a form that allows users to add new food.

### CODE REVIEW

**Review by mahdinoori2000 — CHANGES_REQUESTED** [review]
Hi @richie1988 , 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next ticket but you are almost there!
almost there

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job adding food section to your app 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- **I see you have opened one PR for two ticket. I would be great if you open a PR for each ticket.** 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Comment by mahdinoori2000** [comment]
- [ ] OPTIONAL: You added two task in one PR kindly add one PR for each task. 😃

**Comment by mahdinoori2000** [comment]
issue 1

- [ ]  When I create a food. I can see that food in all users. As the requirement it supposed to add the food in the logged in user. Kindly fix it. paste below code in the food controller in the index method.

@foods = Food.where(user_id: current_user.id).order(created_at: :asc)

**Comment by mahdinoori2000** [comment]
issue 4

- [ ] In the foods. when I want to destroy a food. It take me to the other page instead of deleting it. kindly fix it

**Comment by richie1988** [comment]
okay i wiill fix

**Review by mahdinoori2000 — APPROVED** [review]
Hi @richie1988 
Your project is complete, there is nothing to say than merge it

congratulations

**Pull request merged**
